import type { Metadata } from "next";
import Navigation from "../components/navigation";
import MainContent from "../components/MainContent";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

const greyMonoTrial = localFont({
  src: "./fonts/GreyMonoLLTrialWeb-Book.woff2",
  variable: "--font-grey-mono-trial",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        suppressHydrationWarning
        className={`${geistSans.variable} ${greyMonoTrial.variable} ${geistMono.variable} antialiased overflow-x-hidden`}
      >
        <div className="h-screen flex flex-col">
          {/* <Navigation /> */}
          <MainContent>
            {children}
          </MainContent>
        </div>
      </body>
    </html>
  );
}